name: python tutorial on csdn
on: push

jobs:
  my-job:
    name: python tutorial on csdn
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: python --version

    - name: run python code
      run: |
        python MyPython.py
        cat README.md
        
  
